### ISSUE TITLE
Rendere configurabili i template

### ISSUE THREAD

**Issue by lambrojos** [linkmesrl/ng-form-errors#1]
Al momento il template è error/error.tpl.html

Dovrebbe essere reso configurabile con questo trick:
http://stackoverflow.com/questions/21835471/angular-js-directive-dynamic-templateurl

Sarebbe super figo se si potesse configurare sia globalmente (è una palla configurarli ogni volta)
http://stackoverflow.com/questions/21785999/globally-configuring-angular-directives

che tramite attributo

**Comment by teone** [comment]
@ilgianfra anche secondo me sarebbe più elegante configurarlo globalmente. Sarebbe anche utile la possibile di sovrascriverlo localmente tramite attributo.

**Comment by lambrojos** [comment]
magari leviamo il filtro translate dal template d default?

**Comment by teone** [comment]
Tolto il filtro e reso il template configurabile.
